# ConnectHelp Example

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'
use_frameworks!

platform :ios, '9.0'

target 'ConnectHelp-Swift' do
  use_frameworks!

  pod 'AFNetworking', '~> 3.0'
  pod 'XMPPFramework', '~> 4.0'
  pod 'SVProgressHUD'
end
